default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: modelos_rails_development
  username: postgres
  password: ror2024 
  host: localhost
  port: 5432
